/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Patient;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Encounter;
import model.VitalSigns;

/**
 *
 * @author yaopeixinmac
 */
public class ViewEncounter extends javax.swing.JPanel {
   private JPanel userProcessContainer;
    private Encounter encounter;
    /**
     * Creates new form ViewEncounter
     */
    public ViewEncounter(JPanel upc,Encounter e) {
        initComponents();
        userProcessContainer=upc;
        encounter=e;
        txtName.setText(e.getEncounterTime());
        txtMakeBy.setText(e.getHospital());
        VitalSigns v=e.getVitalsigns();
        if(v==null){
            txtManufacturedYear.setText("");
              txtMinSeats.setText("");
        txtManufacturedYear1.setText("");
        txtMinSeats1.setText("");
        }else{
        txtManufacturedYear.setText(String.valueOf(v.getBloodpressure()));
        txtMinSeats.setText(String.valueOf(v.getAge()));
        txtManufacturedYear1.setText(String.valueOf(v.getWeight()));
        txtMinSeats1.setText(String.valueOf(v.getHigh()));}
        txtName.setEditable(false);
        txtMakeBy.setEditable(false);
        txtManufacturedYear.setEditable(false);
        txtMinSeats.setEditable(false);
        txtManufacturedYear1.setEditable(false);
        txtMinSeats1.setEditable(false);
        jButton2.setEnabled(false);
    }
   public boolean isNumeric(String str){
           Pattern pattern = Pattern.compile("[0-9]*");
           Matcher isNum = pattern.matcher(str);
           if( !isNum.matches() ){
               return false;
           }
           return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMakeBy = new javax.swing.JTextField();
        txtMinSeats = new javax.swing.JTextField();
        lblMakeBy = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        lblManufacturedYear = new javax.swing.JLabel();
        lblMinSeats = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtManufacturedYear = new javax.swing.JTextField();
        lblManufacturedYear1 = new javax.swing.JLabel();
        lblMinSeats1 = new javax.swing.JLabel();
        txtManufacturedYear1 = new javax.swing.JTextField();
        txtMinSeats1 = new javax.swing.JTextField();
        lblTitle1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        txtMakeBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMakeByActionPerformed(evt);
            }
        });

        txtMinSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinSeatsActionPerformed(evt);
            }
        });

        lblMakeBy.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMakeBy.setText("hospital:");

        lblProductName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProductName.setText("time:");

        lblManufacturedYear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblManufacturedYear.setText("bloodpressure:");

        lblMinSeats.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMinSeats.setText("age:");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setText("View Encounter Details");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtManufacturedYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufacturedYearActionPerformed(evt);
            }
        });

        lblManufacturedYear1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblManufacturedYear1.setText("weight(kg):");

        lblMinSeats1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMinSeats1.setText("high(cm):");

        txtManufacturedYear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufacturedYear1ActionPerformed(evt);
            }
        });

        txtMinSeats1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinSeats1ActionPerformed(evt);
            }
        });

        lblTitle1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle1.setText("vital signs");

        jButton1.setText("update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(270, 270, 270)
                            .addComponent(lblProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblManufacturedYear1)
                                .addComponent(lblManufacturedYear)
                                .addComponent(lblMinSeats)
                                .addComponent(lblMakeBy, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMinSeats1))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(lblTitle1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMinSeats1)
                                    .addComponent(txtManufacturedYear1)
                                    .addComponent(txtMinSeats)
                                    .addComponent(txtManufacturedYear)
                                    .addComponent(txtMakeBy, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMakeBy, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMakeBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(lblTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufacturedYear, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtManufacturedYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufacturedYear1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtManufacturedYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinSeats1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinSeats1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(74, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMakeByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMakeByActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMakeByActionPerformed

    private void txtMinSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinSeatsActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtManufacturedYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufacturedYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufacturedYearActionPerformed

    private void txtManufacturedYear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufacturedYear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufacturedYear1ActionPerformed

    private void txtMinSeats1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinSeats1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinSeats1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     txtName.setEditable(true);
        txtMakeBy.setEditable(true);
        txtManufacturedYear.setEditable(true);
        txtMinSeats.setEditable(true);
        txtManufacturedYear1.setEditable(true);
        txtMinSeats1.setEditable(true);
        jButton2.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            if(txtName.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "encounter time can't be empty!!", "Warning", JOptionPane.WARNING_MESSAGE);
                    return;
        }
                if(txtMakeBy.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "encounter hospital can't be empty!!", "Warning", JOptionPane.WARNING_MESSAGE);
                    return;
        }
            if(txtManufacturedYear.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "blood pressure can't be empty!!", "Warning", JOptionPane.WARNING_MESSAGE);
                    return;
        }
               if(txtMinSeats.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "age can't be empty!!", "Warning", JOptionPane.WARNING_MESSAGE);
                    return;
        }
                  if(txtManufacturedYear1.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "weight can't be empty!!", "Warning", JOptionPane.WARNING_MESSAGE);
                    return;
        }
                     if(txtMinSeats1.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "high can't be empty!!", "Warning", JOptionPane.WARNING_MESSAGE);
                    return;
        }
        boolean isnumber1=false;
        boolean isnumber2=false;
        boolean isnumber3=false;
        boolean isnumber4=false;
        isnumber1=isNumeric(txtManufacturedYear.getText());
        isnumber2=isNumeric(txtMinSeats.getText());
        isnumber3=isNumeric(txtManufacturedYear1.getText());
        isnumber4=isNumeric(txtMinSeats1.getText());
           if(!isnumber1){
                    JOptionPane.showMessageDialog(null, "blood pressure must be number type!!", "Warning", JOptionPane.WARNING_MESSAGE);
                    return;
        }
              if(!isnumber2){
                    JOptionPane.showMessageDialog(null, "age must be number type!!", "Warning", JOptionPane.WARNING_MESSAGE);
                    return;
        }
                 if(!isnumber3){
                    JOptionPane.showMessageDialog(null, "weight(kg) must be number type!!", "Warning", JOptionPane.WARNING_MESSAGE);
                    return;
        }
                    if(!isnumber4){
                    JOptionPane.showMessageDialog(null, "high(cm) must be number type!!", "Warning", JOptionPane.WARNING_MESSAGE);
                    return;
        }
        encounter.setEncounterTime(txtName.getText());
        encounter.setHospital(txtMakeBy.getText());
        if(encounter.getVitalsigns()==null){
            encounter.setVitalsigns(new VitalSigns());
        }
        encounter.getVitalsigns().setBloodpressure(Integer.parseInt(txtManufacturedYear.getText()));
        encounter.getVitalsigns().setAge(Integer.parseInt(txtMinSeats.getText()));
         encounter.getVitalsigns().setWeight(Integer.parseInt(txtManufacturedYear1.getText()));
          encounter.getVitalsigns().setHigh(Integer.parseInt(txtMinSeats1.getText()));
           JOptionPane.showMessageDialog(null, "encounter edited successfully!!", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblMakeBy;
    private javax.swing.JLabel lblManufacturedYear;
    private javax.swing.JLabel lblManufacturedYear1;
    private javax.swing.JLabel lblMinSeats;
    private javax.swing.JLabel lblMinSeats1;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JTextField txtMakeBy;
    private javax.swing.JTextField txtManufacturedYear;
    private javax.swing.JTextField txtManufacturedYear1;
    private javax.swing.JTextField txtMinSeats;
    private javax.swing.JTextField txtMinSeats1;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
